[[constraint]]
    name = "github.com/xgfone/go-tools"
    version = "v5.11.0"

[[constraint]]
    name = "github.com/fsnotify/fsnotify"
    version = "v1.4.7"

[[constraint]]
    name = "gopkg.in/yaml.v2"
    version = "v2.2.2"
