[[constraint]]
    name = "github.com/xgfone/go-tools"
    version = "v5.11.0"

[[constraint]]
    name = "github.com/fsnotify/fsnotify"
    version = "v1.4.7"

[[constraint]]
    name = "gopkg.in/yaml.v2"
    version = "v2.2.2"

[[constraint]]
    name = "github.com/BurntSushi/toml"
    version = "v0.3.1"

[[constraint]]
    name = "github.com/samuel/go-zookeeper"
    revision = "c4fab1ac1bec58281ad0667dc3f0907a9476ac47"

[[constraint]]
    name = "github.com/urfave/cli"
    version = "v1.20.0"
